services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: canarias_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d canarias_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_service
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./canarias-frontend
      dockerfile: Dockerfile.dev
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./canarias-frontend:/app
    command: pnpm exec next dev --webpack

volumes:
  backend_node_modules:
  frontend_node_modules:
  postgres_data:
