FROM node:20-alpine

WORKDIR /app

# Compilar módulos nativos
RUN apk add --no-cache python3 make g++

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

# Instalar sin scripts para evitar compilación prematura
RUN pnpm install --ignore-scripts

# Compilar bcrypt para Linux Alpine explícitamente
RUN cd node_modules/.pnpm/bcrypt@5.1.1/node_modules/bcrypt \
    && npm rebuild bcrypt --build-from-source

COPY . .

EXPOSE 3001

CMD ["pnpm", "run", "start:dev"]